### ISSUE TITLE
Non-Urgent: Heads Up

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/responsive-recipe-book#1]
Hi @thomasjbradley

The way the link that we're using to connect to this repository works, many students are running into problems where they clone the repository without forking it, making it impossible for them to push commits. 

Not a difficult fix but wanted to give you a heads up, since I suspect you'll get this question more than once, and our Type teacher doesn't know how to address it.

Cheers!

MacKenzie

**Comment by thomasjbradley** [comment]
Okay—thanks for letting me know.
